spring:
  datasource:
    url: jdbc:mysql://database-1.cyxi5p4qd7xf.ap-northeast-1.rds.amazonaws.com:3306/demo?autoReconnect=true&useSSL=false&serverTimezone=JST
    username: admin
    password: C19ZXgjA6FcDIdMWNQfG
    driver-class-name: com.mysql.cj.jdbc.Driver