spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mixmate?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=JST
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true